### PR TITLE
Rethrow the exception from the underlying method. This fixes #21.

### LINKED ISSUE #21: UndeclaredThrowableException starting to show up
Thank you for a really nice tool. I do have a strange thing happening from time to time since I switched to the new db driver: I get an UndeclaredThrowableException in one of my very simple update calls. The error it should be reporting is (as tested on dev env):

com.google.api.server.spi.response.InternalServerErrorException: insert error
	at com.connvision.napoleon.endpoints.CustomerEndpoint.insertCustomer(CustomerEndpoint.java:88)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...
Caused by: java.sql.SQLException: Duplicate entry entry. ....
...

The stack trace as reported by by Appengine with the new trace driver:

java.lang.reflect.UndeclaredThrowableException
at com.sun.proxy.$Proxy28.executeUpdate (Unknown Source)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate (DelegatingPreparedStatement.java:105)
at org.apache.commons.dbcp.DelegatingPreparedStatement.executeUpdate (DelegatingPreparedStatement.java:105)
at org.apache.commons.dbutils.QueryRunner.update (QueryRunner.java:488)
at org.apache.commons.dbutils.QueryRunner.update (QueryRunner.java:404)
at com.connvision.napoleon.models.Customer.save (Customer.java:100)
at com.connvision.napoleon.endpoints.CustomerEndpoint.insertCustomer (CustomerEndpoint.java:84)
at sun.reflect.GeneratedMethodAccessor572.invoke (Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke (Method.java:42)
at com.google.api.server.spi.SystemService.invokeServiceMethod (SystemService.java:363)
at com.google.api.server.spi.SystemServiceServlet.execute (SystemServiceServlet.java:113)
at com.google.api.server.spi.SystemServiceServlet.doPost (SystemServiceServlet.java:71)
at javax.servlet.http.HttpServlet.service (HttpServlet.java:637)
at javax.servlet.http.HttpServlet.service (HttpServlet.java:717)
at org.mortbay.jetty.servlet.ServletHolder.handle (ServletHolder.java:511)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1166)
at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite (RuleChain.java:176)
at org.tuckey.web.filters.urlrewrite.RuleChain.doRules (RuleChain.java:145)
at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest (UrlRewriter.java:92)
at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter (UrlRewriteFilter.java:389)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter (ServletHandler.java:1157)
at org.mortbay.jetty.servlet.ServletHandler.handle (ServletHandler.java:388)
at org.mortbay.jetty.security.SecurityHandler.handle (SecurityHandler.java:216)
at org.mortbay.jetty.servlet.SessionHandler.handle (SessionHandler.java:182)
at org.mortbay.jetty.handler.ContextHandler.handle (ContextHandler.java:765)
at org.mortbay.jetty.webapp.WebAppContext.handle (WebAppContext.java:418)
at org.mortbay.jetty.handler.HandlerWrapper.handle (HandlerWrapper.java:152)
at org.mortbay.jetty.Server.handle (Server.java:326)
at org.mortbay.jetty.HttpConnection.handleRequest (HttpConnection.java:542)
at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete (HttpConnection.java:923)
at org.mortbay.jetty.HttpConnection.handle (HttpConnection.java:404)
at com.google.tracing.TraceContext$TraceContextRunnable.runInContext (TraceContext.java:453)
at com.google.tracing.TraceContext$TraceContextRunnable$1.run (TraceContext.java:460)
at com.google.tracing.CurrentContext.runInContext (CurrentContext.java:293)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContextNoUnref (TraceContext.java:319)
at com.google.tracing.TraceContext$AbstractTraceContextCallback.runInInheritedContext (TraceContext.java:311)
at com.google.tracing.TraceContext$TraceContextRunnable.run (TraceContext.java:457)
at java.lang.Thread.run (Thread.java:745)

### PR DESCRIPTION
**Pull request by ubschmidt**

### CODE REVIEW

**Comment by cputoaster** [comment]
Is there any release planned to get this out?

**Comment by ubschmidt** [comment]
On it.

**Comment by ubschmidt** [comment]
A new release is now planned for next week. Apologies for the delay.

**Comment by cputoaster** [comment]
Thanks a lot. Great tool and good support.

**Comment by cputoaster** [comment]
Did that release happen? I could not find it on mvnrepository yet.

**Comment by ubschmidt2** [comment]
This is on the radar, but hasn't happened yet. I've created https://github.com/GoogleCloudPlatform/cloud-trace-java-instrumentation/issues/28.

**Pull request merged**
